#!/bin/sh

#
# Script executed at start
#

case "$1" in
  start)
    #udevd --daemon
    #udevadm trigger
    INTERVAL=10
    # Polling interval in seconds

    echo "Waiting for eth0 to connect..."

    while true; do
        # Check if eth0 is up using /sys/class/net
        if [ -d /sys/class/net/eth0 ] && [ "$(cat /sys/class/net/eth0/operstate)" = "up" ]; then
            echo "eth0 is now connected!"
            break
        else
            echo "eth0 is down, checking again in $INTERVAL seconds..."
            sleep $INTERVAL
        fi
    done
    ifconfig

    echo Starting rpi-imager
    UBUNTU_IMAGE=$(wget -q  -O -  http://172.28.0.3/ubuntu/latest)
    PATH=/bin:/sbin:/usr/bin:/usr/sbin rpi-imager --cli http://172.28.0.3/ubuntu/${UBUNTU_IMAGE} /dev/mmcblk0 

    sync
    mkdir -p /bt
    mount /dev/mmcblk0p1 /bt
    SERIAL_NUMBER=$(cat /proc/cpuinfo | awk '/Serial/{print $3; exit}')
    wget -O /bt/meta-data http://172.28.0.3/cloud-init/meta-data?serial_number=${SERIAL_NUMBER}
    wget -O /bt/user-data http://172.28.0.3/cloud-init/user-data?serial_number=${SERIAL_NUMBER}
    umount /bt
    rm -rf /bt
    sync
    reboot -f
    ;;

  stop)
    ;;
  
  *)
    echo "Usage: $0 {start|stop}"
    exit 1  
    ;;
esac

exit $?
